/**
 * Generates the Starlight sidebar from source/SUMMARY.md.
 *
 * Writes a separate module rather than splicing into astro.config.mjs, so generated data and
 * hand-written configuration never share a file or a diff.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseSummary } from './lib/summary.mjs';
import { buildSidebar } from './lib/sidebar-tree.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = `${root}/src/sidebar.generated.mjs`;

const routes = new Map(
  JSON.parse(readFileSync(`${root}/route-map.json`, 'utf8')).map((r) => [r.source, r])
);

/** A page's Starlight slug is its live URL without the leading slash. */
const slugFor = (source) => {
  const route = routes.get(source);
  if (!route) throw new Error(`no route for ${source}`);
  return route.url === '/' ? '' : route.url.slice(1);
};

const entries = parseSummary(readFileSync(`${root}/source/SUMMARY.md`, 'utf8'));
const sidebar = buildSidebar(entries, slugFor);

// A leaf page is one nav row. A parent page is two: the group header (unlinkable, so it
// repeats the page as the group's first item) plus that first item itself. Top-level
// sections are structural buckets, not pages, so they never add a row for themselves.
const countItems = (items) =>
  items.reduce((total, item) => total + 1 + (item.items ? countItems(item.items) : 0), 0);
const count = (groups) => groups.reduce((total, group) => total + countItems(group.items), 0);

writeFileSync(
  OUT,
  '// Generated by scripts/sidebar.mjs from source/SUMMARY.md. Do not edit.\n' +
    `export default ${JSON.stringify(sidebar, null, 2)};\n`
);

console.log(`sections     : ${sidebar.length}`);
console.log(`nav entries  : ${count(sidebar)}`);
console.log(`wrote ${OUT}`);

if (entries.length !== 204) {
  console.error(`expected 204 SUMMARY.md entries, parsed ${entries.length}`);
  process.exit(1);
}
