/**
 * Generates the Starlight sidebar from source/SUMMARY.md.
 *
 * Writes a separate module rather than splicing into astro.config.mjs, so generated data and
 * hand-written configuration never share a file or a diff.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseSummary } from './lib/summary.mjs';
import { buildSidebar } from './lib/sidebar-tree.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = `${root}/src/sidebar.generated.mjs`;

const routes = new Map(
  JSON.parse(readFileSync(`${root}/route-map.json`, 'utf8')).map((r) => [r.source, r])
);

/** A page's Starlight slug is its live URL without the leading slash. */
const slugFor = (source) => {
  const route = routes.get(source);
  if (!route) throw new Error(`no route for ${source}`);
  return route.url === '/' ? '' : route.url.slice(1);
};

const entries = parseSummary(readFileSync(`${root}/source/SUMMARY.md`, 'utf8'));
const sidebar = buildSidebar(entries, slugFor);

// A parent page appears twice in this data: once as the group and once as that group's
// first item, because a Starlight group cannot carry a link. src/components/
// SidebarSublist.astro folds the two back into a single clickable row, so the rendered
// nav is one row per page. Both numbers are reported: a gap between them that is not the
// parent-page count means the two sides have drifted apart. Top-level sections are
// structural buckets, not pages, and never add a row for themselves.
const countItems = (items) =>
  items.reduce((total, item) => total + 1 + (item.items ? countItems(item.items) : 0), 0);
const count = (groups) => groups.reduce((total, group) => total + countItems(group.items), 0);
const countParents = (items) =>
  items.reduce(
    (total, item) => total + (item.items ? 1 + countParents(item.items) : 0),
    0
  );
const parents = sidebar.reduce((total, group) => total + countParents(group.items), 0);

writeFileSync(
  OUT,
  '// Generated by scripts/sidebar.mjs from source/SUMMARY.md. Do not edit.\n' +
    `export default ${JSON.stringify(sidebar, null, 2)};\n`
);

console.log(`sections     : ${sidebar.length}`);
console.log(`data entries : ${count(sidebar)} (${parents} parent pages counted twice)`);
console.log(`rendered rows: ${count(sidebar) - parents}`);
console.log(`wrote ${OUT}`);

if (entries.length !== 204) {
  console.error(`expected 204 SUMMARY.md entries, parsed ${entries.length}`);
  process.exit(1);
}
