/**
 * Checks every image in the built site and writes the alt-text work list.
 *
 * Blocking: every <img> carries an alt attribute, and every <img> src resolves to a file the
 * build actually emitted. That is the brief's Phase 5 image check, done against the bytes on
 * disk rather than over the network.
 *
 * Reporting: the 455 content images that ship with an empty alt, written to
 * reports/alt-text-todo.md for the docs team to fill in. Rows are read from the authored
 * pages under src/content/docs/, which is both the source of truth and what a writer edits,
 * and the row count is checked against the built output: a work list that has drifted from
 * what ships would read as complete work while describing a site nobody is serving.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { emptyAltImages } from './lib/alt-audit.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = `${root}/dist`;
const OUT = `${root}/reports/alt-text-todo.md`;

if (!existsSync(DIST)) {
  console.error('dist/ not found — run `npm run build` first');
  process.exit(1);
}

const routes = JSON.parse(readFileSync(`${root}/route-map.json`, 'utf8'));

// --- the built site -------------------------------------------------------

const files = readdirSync(DIST, { recursive: true })
  .map(String)
  .filter((f) => f.endsWith('.html'));

let images = 0;
const noAltAttribute = [];
const missingFiles = [];
let emptyAltInBuild = 0;
let coverImages = 0;

for (const file of files) {
  const html = readFileSync(`${DIST}/${file}`, 'utf8');
  const main = html.match(/<main\b[\s\S]*?<\/main>/)?.[0] ?? '';
  const covers = [...main.matchAll(/<a\b[^>]*cover-card[\s\S]*?<\/a>/g)].map((m) => m[0]).join('');
  const coverTags = new Set([...covers.matchAll(/<img\b[^>]*>/g)].map((m) => m[0]));
  for (const [tag] of html.matchAll(/<img\b[^>]*>/g)) {
    images++;
    const value = tag.match(/\balt="([^"]*)"/);
    // Astro serialises alt="" as a bare `alt`, which is present-and-empty, not missing.
    if (!value && !/\balt(?=[\s>])/.test(tag)) noAltAttribute.push(`${file}: ${tag.slice(0, 120)}`);
    const src = tag.match(/\bsrc="([^"]*)"/)?.[1];
    if (src?.startsWith('/') && !existsSync(`${DIST}${src.split('?')[0]}`)) {
      missingFiles.push(`${file}: ${src}`);
    }
    if (!main.includes(tag)) continue; // page chrome: the logo
    if (coverTags.has(tag)) { coverImages++; continue; }
    if (!value?.[1]) emptyAltInBuild++;
  }
}

// --- the work list --------------------------------------------------------

const found = [];
for (const route of routes) {
  const page = [`${root}/src/content/docs/${route.target}`, `${root}/src/content/docs/${route.target}x`]
    .find((path) => existsSync(path));
  if (!page) continue;
  for (const image of emptyAltImages(readFileSync(page, 'utf8'))) {
    found.push({ url: route.url, title: route.title, ...image });
  }
}

// Uncaptioned first: those images are announced as nothing at all, while a captioned one at
// least has text beside it. Document order is kept within each group.
const rows = [...found.filter((r) => !r.caption), ...found.filter((r) => r.caption)];
const withCaption = rows.filter((r) => r.caption).length;

const escapePipes = (s) => s.replace(/\|/g, '\\|');
/** Hotlinked third-party images carry 200-character URLs that would make the table unreadable. */
const shorten = (s) => (s.length > 64 ? `${s.slice(0, 63)}…` : s);

const report = [
  '# Images with no alt text',
  '',
  'Generated by `node scripts/verify-images.mjs`. Do not edit by hand.',
  '',
  `${rows.length} images across the documentation ship with an empty \`alt\` attribute, so a`,
  'screen reader announces nothing for them.',
  '',
  'The fix belongs in this repository. `src/content/docs/` is the source of truth and is edited',
  'by hand: give the image alt text in the markdown — `![what it shows](~/assets/…)` — and it',
  'ships on the next deploy.',
  '',
  `The ${rows.length - withCaption} rows with no caption come first: nothing is announced for them at all, and they`,
  `are the ones worth doing first. The remaining ${withCaption} sit under a visible caption, reproduced`,
  'below. That caption is already announced, so alt text for those should describe what the',
  'image *shows* rather than repeat it — duplicating it makes a screen reader read the same',
  'sentence twice.',
  '',
  '| Page | Image | Existing caption |',
  '|---|---|---|',
  ...rows.map((r) => `| [${escapePipes(r.title)}](https://docs.opendialog.ai${r.url}) | \`${escapePipes(shorten(r.asset))}\` | ${escapePipes(r.caption)} |`),
  '',
].join('\n');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, report);

// --- results --------------------------------------------------------------

console.log(`built images       : ${images}`);
console.log(`no alt attribute   : ${noAltAttribute.length}`);
console.log(`src with no file   : ${missingFiles.length}`);
console.log(`cover images       : ${coverImages}`);
console.log(`empty alt in build : ${emptyAltInBuild}`);
console.log(`work-list rows     : ${rows.length} (${withCaption} with a caption)`);
console.log(`\nwrote ${OUT}`);

for (const [label, list] of [
  ['\nImages with no alt attribute at all:', noAltAttribute],
  ['\nImages whose src the build did not emit:', missingFiles],
]) {
  if (!list.length) continue;
  console.error(label);
  for (const item of list) console.error(`  ${item}`);
}

if (rows.length !== emptyAltInBuild) {
  console.error(
    `\nThe work list has ${rows.length} rows but the build ships ${emptyAltInBuild} empty-alt` +
      ' content images. The report describes a site that is not being served.'
  );
}

if (noAltAttribute.length || missingFiles.length || rows.length !== emptyAltInBuild) process.exit(1);
console.log('\nimage check: OK');
